### ISSUE TITLE
探索纯web计算, 去掉后端依赖

### ISSUE THREAD

**Issue by yinxin630** [jiajunsu/calculator_of_Onmyoji#30]
@jiajunsu 大佬能不能分享下你现在的计算逻辑, 我尝试复刻一下, 看看性能表现

**Comment by jiajunsu** [comment]
算法在cal_and_filter.py里面

先过滤：246属性限制，套装类型限制，是否输出御魂限制，是否限定套装

然后遍历全组合，把组合后的总属性，再按照输出结果的要求做过滤，满足条件的写到excel里面
