### ISSUE TITLE
No module named 'calculator_of_Onmyoji'

### ISSUE THREAD

**Issue by everlose** [jiajunsu/calculator_of_Onmyoji#45]
使用命令安装好了依赖

```
$ pip install -r /Users/everlose/Downloads/calculator/requirements.txt
```

接下来运行

```
$ python3 /Users/everlose/Downloads/calculator/calculator_of_Onmyoji/cm_server.py
```

Traceback (most recent call last):
  File "/Users/everlose/Downloads/calculator/calculator_of_Onmyoji/cm_server.py", line 17, in <module>
    from calculator_of_Onmyoji import cal_mitama
ModuleNotFoundError: No module named 'calculator_of_Onmyoji'

额？

**Comment by chujie** [comment]
需要以module的形式执行文件才能正确解析路径，参见下面的讨论
https://github.com/jiajunsu/calculator_of_Onmyoji/commit/0d0ef8324c7fd5c7cdf85d5ca1b34c69a9f8e293#r31631586

**Comment by jiajunsu** [comment]
需要pip install . 
只装依赖但是没装计算器本身

**Comment by sdsau** [comment]
> 需要pip install .
> 只装依赖但是没装计算器本身

pip install -r requirements.txt 执行成功。
pip install .  报错，无法安装，提示信息如下：
D:\workplace_python\yuhun\calculator>pip install .
Processing d:\workplace_python\yuhun\calculator
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\util.py", line 256, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "c:\program files (x86)\python37-32\lib\site-packages\pbr\packaging.py", line 849, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name calculator_of_Onmyoji was given, but was not able to be found.
    error in setup command: Error parsing C:\Users\ZHANG_~1\AppData\Local\Temp\pip-req-build-1lrzec2m\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name calculator_of_Onmyoji was given, but was not able to be found.

**Comment by chujie** [comment]
要从git clone这个repo才有版本信息。
或者可以尝试安装依赖之后可以运行`python3 -m calculator_of_Onmyoji.cm_server`

**Comment by sdsau** [comment]
Web界面打开了，但是无法计算。我想说这个计算器对yys玩家来说是个好东西，要是能弄得对python新手友好一点就好了，起码跟着readme的流程能确实地运行起来。

**Comment by chujie** [comment]
Windows有打包好的版本，还是比较容易使用的吧

**Comment by sdsau** [comment]
我是从nga论坛上给出的网盘地址下载的，下回来跟着readme走，就报上面的错误了。这边打包好的没这问题？我回去试一下。

**Comment by everlose** [comment]
我解决了，我本地装的是 python3 得这么启动
```
python3 -m calculator_of_Onmyoji.cm_server
```

**Comment by everlose** [comment]
> Windows有打包好的版本，还是比较容易使用的吧

打包的那个奇怪的事情更多，我在 win 上启动的时候报某个 dll 缺失，微软官网下了那个 dll 提示本机不适合无法安装。其他网站下载到 dll 但是装进去运行软件仍旧无法解决问题。

所以干脆索性运行源码咯。。
