### ISSUE TITLE
Failed to execute script cal_mitama

### ISSUE THREAD

**Issue by pyshine84** [jiajunsu/calculator_of_Onmyoji#56]
Failed to execute script cal_mitama when I run CMUI190417.
![Capture](https://user-images.githubusercontent.com/56175652/66238947-8b975100-e6f0-11e9-94a4-5b663bad15b3.JPG)

**Comment by jiajunsu** [comment]
Please use cm_server.exe instead of CMUI.

**Comment by pyshine84** [comment]
Thank you!
